language: python
# See tox.ini for env list
python: 3.5  # this is needed to fool travis to have python3.5 as well
env:
- TOXENV=checkmanifest
- TOXENV=flake8-check
- TOXENV=isort-check
- TOXENV=py27-django110
- TOXENV=py27-django16
- TOXENV=py27-django17
- TOXENV=py27-django18
- TOXENV=py27-django19
- TOXENV=py33-django16
- TOXENV=py33-django17
- TOXENV=py33-django18
- TOXENV=py34-django110
- TOXENV=py34-django16
- TOXENV=py34-django17
- TOXENV=py34-django18
- TOXENV=py34-django19
- TOXENV=py35-django110
- TOXENV=py35-django19
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libffi-dev python-dev libssl-dev
install:
- pip install tox>=2.1
script:
- tox
sudo: true
